version: '3.8'

services:
  db:
    image: postgres:16
    container_name: telesales_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telesales_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: telesales_minio
    ports:
      - "9000:9000"  # API通信用ポート
      - "9001:9001"  # ブラウザ確認用（コンソール）ポート
    environment:
      MINIO_ROOT_USER: minioadmin       # ログインID
      MINIO_ROOT_PASSWORD: minioadmin   # ログインパスワード
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data: