"""Initial tables

Revision ID: 94bbd336ab36
Revises: 
Create Date: 2026-08-05 13:20:35.399018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bbd336ab36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_code', sa.String(length=50), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('call_duration', sa.Integer(), nullable=True),
    sa.Column('audio_file_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_records_id'), 'call_records', ['id'], unique=False)
    op.create_index(op.f('ix_call_records_sales_code'), 'call_records', ['sales_code'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_record_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(length=5), nullable=True),
    sa.Column('purchase_probability', sa.Float(), nullable=True),
    sa.Column('customer_interest', sa.Text(), nullable=True),
    sa.Column('concerns', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['call_record_id'], ['call_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_record_id')
    )
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_record_id', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.String(length=20), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['call_record_id'], ['call_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_id'), 'transcripts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_call_records_sales_code'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_id'), table_name='call_records')
    op.drop_table('call_records')
    # ### end Alembic commands ###
